Add missing semicolon to make desktop-file-validate happy
desktop-file-validate gnote.desktop:
error: value "sporo?ilce;zamisel;ideja;povezava;organizacija" for locale
string list key "Keywords[sl]" in group "Desktop Entry" does not have a
semicolon (';') as trailing character