Fix build
has_buffer and is_loaded both expect to return a bool, so returning
plain m_buffer won't cut it

Fixes build error

[   89s] In file included from ../../../src/noteaddin.hpp:38:0,
[   89s]                  from backlinksnoteaddin.hpp:27,
[   89s]                  from backlinksnoteaddin.cpp:25:
[   89s] ../../../src/note.hpp: In member function 'bool gnote::Note::has_buffer() const':
[   89s] ../../../src/note.hpp:127:14: error: cannot convert 'const Glib::RefPtr<gnote::NoteBuffer>' to 'bool' in return
[   89s]        return m_buffer;
[   89s]               ^~~~~~~~
[   89s] ../../../src/note.hpp: In member function 'bool gnote::Note::is_loaded() const':
[   89s] ../../../src/note.hpp:142:23: error: cannot convert 'const Glib::RefPtr<gnote::NoteBuffer>' to 'bool' in return
[   89s]        return (m_buffer);

https://bugzilla.gnome.org/show_bug.cgi?id=770541